### ISSUE TITLE
Plot IDs not showing / cannot delete plots

### ISSUE THREAD

**Issue by CtrlAltCuteness** [josh-greenlaw/minecraft-discord-bot#17]
Since one of the updates, PlotBot no longer shows IDs for existing as well as for plots just created. See image for reference (My roles allow all commands)

![Screenshot_20200726-193506](https://user-images.githubusercontent.com/8661411/88498353-c0261300-cf77-11ea-9ab2-c56e3c70d76b.png)

**Comment by josh-greenlaw** [comment]
Thanks for the report, I'll look into it ASAP!

**Comment by josh-greenlaw** [comment]
@CtrlAltCuteness, I've pushed a quick patch to resolve the the immediate issue. Note that currently Ids will only show up when searching based on a user's discord long ID (or mentioning them). The %plot search... function is still not showing IDs, so I'm going to leave this issue open.

**Comment by josh-greenlaw** [comment]
Resolved Id missing in search functions as well.
