### ISSUE TITLE
Plot delete lack of permission, even when serverIsConfigured is false

### ISSUE THREAD

**Issue by CtrlAltCuteness** [josh-greenlaw/minecraft-discord-bot#18]
![Screenshot_20200727-135551](https://user-images.githubusercontent.com/8661411/88591557-607c4600-d011-11ea-9775-f9daaae11dbe.png)

**Comment by josh-greenlaw** [comment]
@CtrlAltCuteness this should also be resolved now. Thank you for submitting these bug reports!!
